import { cn } from "@/lib/utils"
import "./globals.css"
import type { Metadata } from "next"
import { Inter, Poppins } from "next/font/google"
import { AppProviders } from "@/providers/root"
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })
const poppins = Poppins({
  subsets: ["latin", "devanagari", "latin-ext"],
  variable: "--poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(inter.className, poppins.variable, "__first")}>
          <AppProviders>{children}</AppProviders>
        </body>
      </html>
    </ClerkProvider>
  )
}
